### ISSUE TITLE
Ability to configure worker and volume types/sizes for GCP and Azure ClusterPools

### ISSUE THREAD

**Issue by gurnben** [open-cluster-management/cm-cli#75]
## Summary of Problem

Currently, the user can provide the following details in the vlaues.yaml:
```
  aws:
    master:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 4000
        size: 100
        type: gp2
    worker:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 2000
        size: 100
        type: gp2
```

but they cannot provide machine types and volume details for GCP or Azure (or other platforms) - these will need overridden at times, so we should allow this function as well!
